version: "3.9"

services:
  vueapp:
    build: .
    container_name: vueapp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vueapp.rule=Host(`karelpelcak.eu`)"
      - "traefik.http.routers.vueapp.entrypoints=websecure"
      - "traefik.http.routers.vueapp.tls=true"
      - "traefik.http.routers.vueapp.tls.certresolver=myresolver"
      - "traefik.http.services.vueapp.loadbalancer.server.port=5000"
    networks:
      - web

  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pelcak.karel@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  traefik-certificates:

