version: "3.9"

services:
  vueapp:
    build: .
    container_name: vueapp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vueapp.rule=Host(`karelpelcak.eu`)"
      - "traefik.http.routers.vueapp.entrypoints=websecure"
      - "traefik.http.routers.vueapp.tls=true"
      - "traefik.http.routers.vueapp.tls.certresolver=myresolver"
      - "traefik.http.services.vueapp.loadbalancer.server.port=5000" # Důležité! Port v kontejneru, kde běží serve

      - "traefik.http.routers.redirect.rule=Host(`karelpelcak.eu`)"
      - "traefik.http.routers.redirect.entrypoints=web"
      - "traefik.http.routers.redirect.middlewares=redirect-to-https"
    networks:
      - web

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pelcak.karel@gmail.com" # změň na tvůj email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  traefik-certificates:
